### ISSUE TITLE
feature/MN-04: Добавить цвета в файл color.scss

### ISSUE THREAD

**Issue by nikitagorbunov** [DaerioFrixell/masterN#6]

**Comment by DaerioFrixell** [comment]
мне нужно фотка, как вы на проекте это оформляете. То, что ты на созвоне показывал у вас на работе. Там огромный список был и я хочу у вас структуру забрать. 
Цвета выбрать не проблема, а вот как вы это оборачиваете внутри файлу в плане вложенностей и стилистики - это мне увидеть нужно, чтоб сделать.

Скинь вк скрин прям из SCSs со стилями у вас. Мне строчек 30 нужно увидеть хотя бы, целиков файл не нужен)
Ну или на созвоне покажешь потом, я заскриню сам прост
